"""crate tables

Revision ID: f3a454b9a11e
Revises:
Create Date: 2026-01-29 22:06:10.307121+03:00

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3a454b9a11e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "agency",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "building",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_closure",
        sa.Column("ancestor_id", sa.BigInteger(), nullable=False),
        sa.Column("descendant_id", sa.BigInteger(), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("depth <= 3", name="ck_activity_closure_depth_max"),
        sa.CheckConstraint("depth >= 0", name="ck_activity_closure_depth_min"),
        sa.ForeignKeyConstraint(
            ["ancestor_id"], ["activity.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["descendant_id"], ["activity.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "ancestor_id",
            "descendant_id",
            name="uq_activity_closure_ancestor_descendant",
        ),
    )
    op.create_index(
        "ix_activity_closure_ancestor_depth",
        "activity_closure",
        ["ancestor_id", "depth"],
        unique=False,
    )
    op.create_table(
        "activity_name",
        sa.Column("activity_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activity.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "activity_id", name="uq_activity_name_activity_id"
        ),
    )
    op.create_index(
        "ix_activity_name_name", "activity_name", ["name"], unique=False
    )
    op.create_table(
        "activity_parent",
        sa.Column("activity_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "activity_id <> parent_id", name="ck_activity_parent_not_self"
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activity.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["activity.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "activity_id", name="uq_activity_parent_activity_id"
        ),
    )
    op.create_table(
        "agency_activity",
        sa.Column("agency_id", sa.BigInteger(), nullable=False),
        sa.Column("activity_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["activity_id"], ["activity.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agency.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agency_id",
            "activity_id",
            name="uq_agency_activity_agency_id_activity_id",
        ),
    )
    op.create_index(
        "ix_agency_activity_activity_id",
        "agency_activity",
        ["activity_id"],
        unique=False,
    )
    op.create_table(
        "agency_building",
        sa.Column("agency_id", sa.BigInteger(), nullable=False),
        sa.Column("building_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agency.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["building_id"], ["building.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agency_id", name="uq_agency_building_agency_id"),
    )
    op.create_index(
        "ix_agency_building_building_id",
        "agency_building",
        ["building_id"],
        unique=False,
    )
    op.create_table(
        "agency_name",
        sa.Column("agency_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agency.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agency_id", name="uq_agency_name_agency_id"),
    )
    op.create_index(
        "ix_agency_name_name", "agency_name", ["name"], unique=False
    )
    op.create_table(
        "agency_phone",
        sa.Column("agency_id", sa.BigInteger(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agency.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "agency_id", "phone", name="uq_agency_phone_agency_id_phone"
        ),
    )
    op.create_index(
        "ix_agency_phone_phone", "agency_phone", ["phone"], unique=False
    )
    op.create_table(
        "building_address",
        sa.Column("building_id", sa.BigInteger(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["building_id"], ["building.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "building_id", name="uq_building_address_building_id"
        ),
    )
    op.create_index(
        "ix_building_address_address",
        "building_address",
        ["address"],
        unique=False,
    )
    op.create_table(
        "building_geo",
        sa.Column("building_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["building_id"], ["building.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("building_id", name="uq_building_geo_building_id"),
    )
    op.create_index(
        "ix_building_geo_geom",
        "building_geo",
        ["geom"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_building_geo_geom",
        table_name="building_geo",
        postgresql_using="gist",
    )
    op.drop_table("building_geo")
    op.drop_index("ix_building_address_address", table_name="building_address")
    op.drop_table("building_address")
    op.drop_index("ix_agency_phone_phone", table_name="agency_phone")
    op.drop_table("agency_phone")
    op.drop_index("ix_agency_name_name", table_name="agency_name")
    op.drop_table("agency_name")
    op.drop_index(
        "ix_agency_building_building_id", table_name="agency_building"
    )
    op.drop_table("agency_building")
    op.drop_index(
        "ix_agency_activity_activity_id", table_name="agency_activity"
    )
    op.drop_table("agency_activity")
    op.drop_table("activity_parent")
    op.drop_index("ix_activity_name_name", table_name="activity_name")
    op.drop_table("activity_name")
    op.drop_index(
        "ix_activity_closure_ancestor_depth", table_name="activity_closure"
    )
    op.drop_table("activity_closure")
    op.drop_table("building")
    op.drop_table("agency")
    op.drop_table("activity")
    # ### end Alembic commands ###
